set(LV_EDITOR_PROJECT_SOURCES)
list(
  APPEND
  LV_EDITOR_PROJECT_SOURCES
  ${CMAKE_CURRENT_LIST_DIR}/components/buttons/button_circle/button_circle_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/buttons/button/button_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/cards/card_clock/card_clock_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/cards/card_empty/card_empty_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/cards/card_info/card_info_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/cards/card_weather/card_weather_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/controls/arc_box/arc_box_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/controls/arc/arc_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/controls/checkbox/checkbox_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/controls/roller/roller_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/controls/slider_box/slider_box_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/controls/slider/slider_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/controls/switch/switch_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/controls/value_setter/value_setter_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/header/header/header_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/header/icon/icon_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/headings/h1/h1_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/headings/h2/h2_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/headings/h3/h3_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/headings/h4/h4_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/layout/column/column_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/layout/container/container_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/layout/panel/panel_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/layout/row/row_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/layout/spacer/spacer_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/list/list_container/list_container_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/list/list_item/list_item_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/visualizers/chart/chart_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/visualizers/date/date_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/visualizers/image_mono/image_mono_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/visualizers/image/image_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/visualizers/theme/theme_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/visualizers/time/time_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/visualizers/value_large/value_large_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/visualizers/value_medium/value_medium_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/visualizers/value_small/value_small_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/font_lg_bold_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/font_lg_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/font_md_bold_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/font_md_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/font_sm_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/font_xl_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/font_xs_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/font_xxl_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/icon_check_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/icon_minus_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/icon_plus_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/icon_wifi_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/image_alarm_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/image_weather_foggy_data.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/screen_home_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/starter_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/starter.c)